//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitsRatingTool.GuiApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitsRatingTool.GuiApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///All Rights Reserved
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_Avalonia {
            get {
                return ResourceManager.GetString("LICENSE_Avalonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright (Unpublished--all rights reserved under the copyright laws of
        ///the United States), U.S. Government as represented by the Administrator
        ///of the National Aeronautics and Space Administration.  No copyright is
        ///claimed in the United States under Title 17, U.S. Code.
        ///
        ///Permission to freely use, copy, modify, and distribute this software
        ///and its documentation without fee is hereby granted, provided that this
        ///copyright notice and disclaimer of warranty appears in all copies.
        ///
        ///DISCLAIMER:
        ///
        ///THE SOF [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_CFITSIO {
            get {
                return ResourceManager.GetString("LICENSE_CFITSIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minpack Copyright Notice (1999) University of Chicago.  All rights reserved
        ///
        ///Redistribution and use in source and binary forms, with or
        ///without modification, are permitted provided that the
        ///following conditions are met:
        ///
        ///1. Redistributions of source code must retain the above
        ///copyright notice, this list of conditions and the following
        ///disclaimer.
        ///
        ///2. Redistributions in binary form must reproduce the above
        ///copyright notice, this list of conditions and the following
        ///disclaimer in the documentation [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_CMinpack {
            get {
                return ResourceManager.GetString("LICENSE_CMinpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright: Thomas McGlynn 1997-2007.
        /// 
        ///The CSharpFITS package is a C# port of Tom McGlynn&apos;s
        /// nom.tam.fits Java package, initially ported by  Samuel Carliles
        ///
        ///Copyright: 2007 Virtual Observatory - India. 
        ///
        ///Use is subject to license terms mentioned below:
        ///
        ///LICENCE-TERMS:
        ///Redistribution and use in source and binary forms, with or without
        ///modification, are permitted provided that the following conditions are met:
        ///     * Redistributions of source code must retain the above copyright
        ///       notice, t [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_CSharpFITS {
            get {
                return ResourceManager.GetString("LICENSE_CSharpFITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to t [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_DotNet {
            get {
                return ResourceManager.GetString("LICENSE_DotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The MIT License (MIT)
        ///
        ///Copyright (c) 2013-2021 Maksim Volkau
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The a [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_DryIoc {
            get {
                return ResourceManager.GetString("LICENSE_DryIoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die                     GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        ///t [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_FITSRatingTool {
            get {
                return ResourceManager.GetString("LICENSE_FITSRatingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The MIT License (MIT)
        ///
        ///Copyright (c) 2007 James Newton-King
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of
        ///this software and associated documentation files (the &quot;Software&quot;), to deal in
        ///the Software without restriction, including without limitation the rights to
        ///use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
        ///the Software, and to permit persons to whom the Software is furnished to do so,
        ///subject to the following conditions:
        ///
        ///The ab [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_JsonDotNet {
            get {
                return ResourceManager.GetString("LICENSE_JsonDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright (c) 2002-2022 Math.NET
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_MathDotNet {
            get {
                return ResourceManager.GetString("LICENSE_MathDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MIT License
        ///
        ///Copyright (c) 2021 https://matheval.org
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above cop [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_MathEval {
            get {
                return ResourceManager.GetString("LICENSE_MathEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The MIT License (MIT)
        ///
        ///Copyright (c) 2014 OxyPlot contributors
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a
        ///copy of this software and associated documentation files (the
        ///&quot;Software&quot;), to deal in the Software without restriction, including
        ///without limitation the rights to use, copy, modify, merge, publish,
        ///distribute, sublicense, and/or sell copies of the Software, and to
        ///permit persons to whom the Software is furnished to do so, subject to
        ///the following conditions:
        ///
        ///Th [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_OxyPlot {
            get {
                return ResourceManager.GetString("LICENSE_OxyPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The MIT License (MIT)
        ///
        ///Copyright (c) Wiesław Šoltés
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copy [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_PanAndZoom {
            get {
                return ResourceManager.GetString("LICENSE_PanAndZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PixInsight Class Library License Version 1.0
        ///===============================================================================
        ///
        ///Copyright (c) 2003-2022, Pleiades Astrophoto S.L. All Rights Reserved.
        ///
        ///Redistribution and use in both source and binary forms, with or without
        ///modification, is permitted provided that the following conditions are met:
        ///
        ///1. All redistributions of source code must retain the above copyright notice,
        ///   this list of conditions and the following disclaimer.
        ///
        ///2. All redistributions in bina [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_PCL {
            get {
                return ResourceManager.GetString("LICENSE_PCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///	pthreads-win32 - a POSIX threads library for Microsoft Windows
        ///
        ///
        ///This file is Copyrighted
        ///------------------------
        ///
        ///    This file is covered under the following Copyright:
        ///
        ///	Copyright (C) 2001,2006 Ross P. Johnson
        ///	All rights reserved.
        ///
        ///	Everyone is permitted to copy and distribute verbatim copies
        ///	of this license document, but changing it is not allowed.
        ///
        ///Pthreads-win32 is covered by the GNU Lesser General Public License
        ///------------------------------------------------------------------
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_PThreads {
            get {
                return ResourceManager.GetString("LICENSE_PThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die                    GNU LESSER GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///
        ///  This version of the GNU Lesser General Public License incorporates
        ///the terms and conditions of version 3 of the GNU General Public
        ///License, supplemented by the additional permissions listed below.
        ///
        ///  0. Additional Def [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_SEP {
            get {
                return ResourceManager.GetString("LICENSE_SEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die StreamJsonRpc
        ///Copyright (c) Microsoft Corporation
        ///All rights reserved. 
        ///
        ///MIT License
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the foll [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_StreamJsonRpc {
            get {
                return ResourceManager.GetString("LICENSE_StreamJsonRpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft.VisualStudio.Threading
        ///Copyright (c) Microsoft Corporation
        ///All rights reserved. 
        ///
        ///MIT License
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so,  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE_VSThreading {
            get {
                return ResourceManager.GetString("LICENSE_VSThreading", resourceCulture);
            }
        }
    }
}
